jwt:
  secret: gQq2wbSH1ohB9ZC+mfZLVkffzIqZX4MsOMhMRDFtO3Rb+dGjtrfhY02SHWmU5OYfZaPivLLch1O2tAGsVDJCVg==
  access-token-expiration: 900000   # 15분 (ms 단위)
  refresh-token-expiration: 604800000 # 7일

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deal4u
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: never
      # data-locations: classpath:data-ci.sql

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 222701460360-d7e9hvsqdo1evm0k7hnkvg1sgl02a6bk.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/api/v1/login/google"
            scope:
              - email
              - profile
          kakao:
            client-id: dummy-kakao-client-id # 발급 받은 Client ID
            client-secret: dummy-kakao-client-secret # 발급 받은 Client Secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao
          naver:
            client-id: dummy-naver-client-id # 발급 받은 Client ID
            client-secret: dummy-naver-client-secret # 발급 받은 Client Secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정
toss:
  secret-key: test_sk_DpexMgkW36wJdWA1DM74VGbR5ozO