name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Checkstyle only
        run: ./gradlew checkstyleMain

      - name: Publish Checkstyle Report
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        with:
          path: '**/build/reports/checkstyle/*.xml'


  test:
    runs-on: ubuntu-latest
    needs: checkstyle
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test -Dspring.profiles.active=ci
        env:
          TOSS_SECRET_KEY: ${{ secrets.TOSS_SECRET_KEY }}
          S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
          S3_REGION: ${{secrets.S3_REGION}}
          S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}
          S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}

  build:
    runs-on: ubuntu-latest
    needs: [ checkstyle, test ]
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build project only (skip test and checkstyle)
        run: ./gradlew build -x test -x checkstyleMain