name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Checkstyle only
        run: ./gradlew checkstyleMain

      - name: Publish Checkstyle Report
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        with:
          path: '**/build/reports/checkstyle/*.xml'


  test:
    runs-on: ubuntu-latest
    needs: checkstyle
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: SPRING_PROFILES_ACTIVE=ci ./gradlew test
        env:
          SMTP_HOST: ${{secrets.SMTP_HOST}}
          SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
          SMTP_PORT: ${{secrets.SMTP_PORT}}
          SMTP_USERNAME: ${{secrets.SMTP_USERNAME}}
          TOSS_SECRET_KEY: ${{ secrets.TOSS_SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          HOST_URL: ${{secrets.HOST_URL}}
          S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
          S3_REGION: ${{secrets.S3_REGION}}
          S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}
          S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}

  build:
    runs-on: ubuntu-latest
    needs: [ checkstyle, test ]
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build project only (skip test and checkstyle)
        run: SPRING_PROFILES_ACTIVE=ci ./gradlew build -x test -x checkstyleMain
